language: python
python:
  - "2.7"

# command to install dependencies
install:
  - "pip install pipenv --upgrade"
  - "pipenv install --dev --skip-lock"
  
# command to run tests
script: "python manage.py test"

# command to run the dependencies
# script:
#  - "pipenv run pytest -n 8 tests"

notifications:
  email:
    recipients:
      - llegrand26@yahoo.com
      - psarrazin@seti.org
    on_success: always
    on_failure: always
  slack: plquant:LVZ74IbPwglpPUs1CQF8jKnl
