"""empty message

Revision ID: 07b659c01096
Revises: 
Create Date: 2017-12-05 19:38:12.432571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b659c01096'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'modes', sa.Column('mode_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'modes', 'modes', ['mode_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modes', type_='foreignkey')
    op.drop_column(u'modes', 'mode_id')
    op.drop_table('users')
    op.drop_table('user')
    # ### end Alembic commands ###
