"""empty message

Revision ID: 1aceedd16ca5
Revises: 
Create Date: 2017-12-06 14:20:33.126339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aceedd16ca5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('qlambda', sa.Float(), nullable=True),
    sa.Column('qtarget', sa.String(length=64), nullable=True),
    sa.Column('fwhma', sa.Float(), nullable=True),
    sa.Column('fwhmb', sa.Float(), nullable=True),
    sa.Column('inventory', sa.String(length=64), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modes')
    op.drop_table('users')
    # ### end Alembic commands ###
