"""empty message

Revision ID: 23b53bbc73b7
Revises: 1aceedd16ca5
Create Date: 2018-01-22 13:00:32.717733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23b53bbc73b7'
down_revision = '1aceedd16ca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modes', sa.Column('initial', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modes', 'initial')
    # ### end Alembic commands ###
