"""empty message

Revision ID: 7361abbc936a
Revises: c9eda192a656
Create Date: 2017-12-05 20:16:17.528629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7361abbc936a'
down_revision = 'c9eda192a656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'modes_author_id_fkey', 'modes', type_='foreignkey')
    op.create_foreign_key(None, 'modes', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modes', type_='foreignkey')
    op.create_foreign_key(u'modes_author_id_fkey', 'modes', 'modes', ['author_id'], ['id'])
    # ### end Alembic commands ###
