"""empty message

Revision ID: b3d5324247be
Revises: 07b659c01096
Create Date: 2017-12-05 19:55:25.388360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d5324247be'
down_revision = '07b659c01096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('modes', 'inventory',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('modes', 'title',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_constraint(u'modes_inventory_key', 'modes', type_='unique')
    op.drop_constraint(u'modes_qtarget_key', 'modes', type_='unique')
    op.drop_constraint(u'modes_title_key', 'modes', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'modes_title_key', 'modes', ['title'])
    op.create_unique_constraint(u'modes_qtarget_key', 'modes', ['qtarget'])
    op.create_unique_constraint(u'modes_inventory_key', 'modes', ['inventory'])
    op.alter_column('modes', 'title',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('modes', 'inventory',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
