"""empty message

Revision ID: c9eda192a656
Revises: b3d5324247be
Create Date: 2017-12-05 20:04:40.814924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9eda192a656'
down_revision = 'b3d5324247be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modes', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'modes_mode_id_fkey', 'modes', type_='foreignkey')
    op.create_foreign_key(None, 'modes', 'modes', ['author_id'], ['id'])
    op.drop_column('modes', 'mode_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modes', sa.Column('mode_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'modes', type_='foreignkey')
    op.create_foreign_key(u'modes_mode_id_fkey', 'modes', 'modes', ['mode_id'], ['id'])
    op.drop_column('modes', 'author_id')
    # ### end Alembic commands ###
