"""empty message

Revision ID: e3170f7799b4
Revises: 
Create Date: 2017-11-16 20:52:10.212732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3170f7799b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('qlambda', sa.Float(), nullable=True),
    sa.Column('qtarget', sa.String(length=64), nullable=True),
    sa.Column('fwhma', sa.Float(), nullable=True),
    sa.Column('fwhmb', sa.Float(), nullable=True),
    sa.Column('inventory', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory'),
    sa.UniqueConstraint('qtarget'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mode')
    # ### end Alembic commands ###
